import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'zh_Hans'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key, {String? defaultValue}) {
    String result = (kTranslationsMap[key] ?? {})[locale.toString()] ??
        (defaultValue ?? '');
    return result;
  }

  String getVariableText({
    String? enText = '',
    String? zh_HansText = '',
  }) =>
      [enText, zh_HansText][languageIndex] ?? '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'byoctihc': {
      'en': 'Welcome to DigitalFactory',
      'de': 'Willkommen bei DigitalFactory',
      'fr': 'Bienvenue sur DigitalFactory',
      'ja': 'デジタルファクトリーへようこそ',
      'zh_Hans': '欢迎来到数字工厂',
    },
    '7m5o70u8': {
      'en': 'Hello Guest! Welcome back.',
      'de': 'Hallo Gast! Willkommen zurück.',
      'fr': 'Bonjour Invité ! Content de te revoir.',
      'ja': 'こんにちはゲスト！おかえり。',
      'zh_Hans': '客人您好！欢迎回来。',
    },
    'qbhcr7z8': {
      'en': 'Create',
      'de': 'Schaffen',
      'fr': 'Créer',
      'ja': '作成',
      'zh_Hans': '创造',
    },
    '8dok0sfa': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'hmzlh35e': {
      'en': 'OVERVIEW',
      'de': 'ÜBERBLICK',
      'fr': 'APERÇU',
      'ja': '概要',
      'zh_Hans': '概述',
    },
    'gh6q6yoe': {
      'en': 'TOTAL OUTPUT',
      'de': 'GESAMTLEISTUNG',
      'fr': 'SORTIE TOTALE',
      'ja': '総生産高',
      'zh_Hans': '总产出',
    },
    'saf5ng86': {
      'en': '500.20B',
      'de': '500.20B',
      'fr': '500.20B',
      'ja': '500.20B',
      'zh_Hans': '500.20B',
    },
    '21x8wjwg': {
      'en': 'AVG EFFICENCY ',
      'de': 'DURCHSCHNITTLICHE EFFIZIENZ',
      'fr': 'EFFICACITÉ MOYENNE',
      'ja': '平均効率',
      'zh_Hans': '平均效率',
    },
    'nilobwjj': {
      'en': '95.76%',
      'de': '95,76 %',
      'fr': '95,76 %',
      'ja': '95.76%',
      'zh_Hans': '95.76%',
    },
    '10re4v7b': {
      'en': 'OUTPUT TODAY',
      'de': 'AUSGABE HEUTE',
      'fr': 'SORTIE AUJOURD\'HUI',
      'ja': '今日のアウトプット',
      'zh_Hans': '今天的产量',
    },
    'arnt20hm': {
      'en': '0.25M',
      'de': '0,25 M',
      'fr': '0.25M',
      'ja': '0.25M',
      'zh_Hans': '0.25M',
    },
    'sgyjfrph': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    '4vnhjwga': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    'i3pymgyw': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    'ven1qpwz': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    'zgvfsj1c': {
      'en': 'Notifications',
      'de': 'Benachrichtigungen',
      'fr': 'Avis',
      'ja': '通知',
      'zh_Hans': '通知',
    },
    'vi2nyjjh': {
      'en': 'Below are you new notifications.',
      'de': 'Unten sind Ihre neuen Benachrichtigungen.',
      'fr': 'Vous trouverez ci-dessous de nouvelles notifications.',
      'ja': '以下は新しい通知です。',
      'zh_Hans': '以下是您的新通知。',
    },
    'w20qzy9r': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'cunsd5z0': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'e2vfwyui': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'gw7j3ise': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'j1uzjil0': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'vww8fm3v': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'vrl92nk0': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'ypwg6dnl': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    '3gcwkub9': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'qjifeynz': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'qo1r6531': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'gxsnut94': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'y3jglg7t': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // devicesAlt
  {
    'vibf8vqe': {
      'en': 'Your Device',
      'de': 'Ihr Gerät',
      'fr': 'Votre appareil',
      'ja': 'あなたのデバイス',
      'zh_Hans': '你的设备',
    },
    'wqd27t6p': {
      'en': 'Your projects are below',
      'de': 'Ihre Projekte sind unten',
      'fr': 'Vos projets ci-dessous',
      'ja': 'あなたのプロジェクトは以下のとおりです',
      'zh_Hans': '您的项目如下',
    },
    'cthhf2m6': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'wl92yxg8': {
      'en': 'Notifications',
      'de': 'Benachrichtigungen',
      'fr': 'Avis',
      'ja': '通知',
      'zh_Hans': '通知',
    },
    '88ighwvg': {
      'en': 'Below are you new notifications.',
      'de': 'Unten sind Ihre neuen Benachrichtigungen.',
      'fr': 'Vous trouverez ci-dessous de nouvelles notifications.',
      'ja': '以下は新しい通知です。',
      'zh_Hans': '以下是您的新通知。',
    },
    'dow75c37': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'imvp4zoh': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'yg0bk3bt': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'x42j95vy': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'zp6iay4z': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'ydsh35x3': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'pgfbshj3': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'x3mgsj5a': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'qu81rf0d': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '6yl6afsi': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'ohgm7pn6': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'yvgap105': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'ryjm6uw3': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Language
  {
    'cepltokh': {
      'en': 'Hello World',
      'de': 'Hallo Welt',
      'fr': 'Bonjour le monde',
      'ja': 'こんにちは世界',
      'zh_Hans': '你好世界',
    },
    '1ujk81ko': {
      'en': 'English',
      'de': 'Englisch',
      'fr': 'Anglais',
      'ja': '英語',
      'zh_Hans': '英语',
    },
    'qhhqh5l4': {
      'en': 'chinese',
      'de': 'Chinesisch',
      'fr': 'chinois',
      'ja': '中文',
      'zh_Hans': '中文',
    },
    'pa61qrgm': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // responsiveTest
  {
    'cbhgiwm8': {
      'en': 'Your Projects',
      'de': 'Ihre Projekte',
      'fr': 'Tes projets',
      'ja': 'あなたのプロジェクト',
      'zh_Hans': '您的项目',
    },
    '0sls6kw7': {
      'en': 'Your projects are below, check it out.',
      'de': 'Ihre Projekte sind unten, sehen Sie es sich an.',
      'fr': 'Vos projets sont ci-dessous, consultez-les.',
      'ja': 'あなたのプロジェクトは以下にあります。チェックしてください。',
      'zh_Hans': '你的项目在下面，检查一下。',
    },
    '53zys4hr': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'tvwlt2ke': {
      'en': 'Credit Card',
      'de': 'Kreditkarte',
      'fr': 'Carte de crédit',
      'ja': 'クレジットカード',
      'zh_Hans': '信用卡',
    },
    '2w8mpf1g': {
      'en': 'Budget',
      'de': 'Budget',
      'fr': 'Budget',
      'ja': 'バジェット',
      'zh_Hans': '预算',
    },
    '1m15wkzq': {
      'en': 'Balance',
      'de': 'Balance',
      'fr': 'Solde',
      'ja': 'バランス',
      'zh_Hans': '平衡',
    },
    'c871wtzn': {
      'en': '\$7,630',
      'de': '\$7.630',
      'fr': '7 630 \$',
      'ja': '\$7,630',
      'zh_Hans': '\$7,630',
    },
    'dasfz3nr': {
      'en': '**** 0149',
      'de': '**** 0149',
      'fr': '**** 0149',
      'ja': '**** 0149',
      'zh_Hans': '**** 0149',
    },
    'zdy0xzhd': {
      'en': '05/25',
      'de': '25.05',
      'fr': '25/05',
      'ja': '05/25',
      'zh_Hans': '05/25',
    },
    'o0491zf3': {
      'en': 'Spending',
      'de': 'Ausgaben',
      'fr': 'Dépenses',
      'ja': '支出',
      'zh_Hans': '开支',
    },
    'l7olqxp3': {
      'en': 'Tab View 2',
      'de': 'Registerkartenansicht 2',
      'fr': 'Onglet Affichage 2',
      'ja': 'タブ ビュー 2',
      'zh_Hans': '选项卡视图 2',
    },
    'v68aozff': {
      'en': 'Balance',
      'de': 'Balance',
      'fr': 'Solde',
      'ja': 'バランス',
      'zh_Hans': '平衡',
    },
    'thih5h3p': {
      'en': 'Avg. Spend',
      'de': 'Durchschn. Ausgeben',
      'fr': 'Moy. Passer',
      'ja': '平均払う',
      'zh_Hans': '平均。花费',
    },
    't4di97cf': {
      'en': '\$25,205',
      'de': '25.205 \$',
      'fr': '25 205 \$',
      'ja': '\$25,205',
      'zh_Hans': '25,205 美元',
    },
    'gk4ap4gt': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    '2msyutna': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    'pmfnbk4l': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    'zzw80byt': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    '51d9zxo7': {
      'en': 'Recent Transactions',
      'de': 'kürzliche Transaktionen',
      'fr': 'transactions récentes',
      'ja': '最近の取引',
      'zh_Hans': '最近的交易',
    },
    'qqt7nhgo': {
      'en': 'A list of all your transactions this week.',
      'de': 'Eine Liste all Ihrer Transaktionen in dieser Woche.',
      'fr': 'Une liste de toutes vos transactions cette semaine.',
      'ja': '今週のすべての取引のリスト。',
      'zh_Hans': '本周所有交易的清单。',
    },
    'zget5n63': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '1p9sfg9v': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'aznzw4f3': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '4ez6kftz': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'uht4kun8': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'z30jzbsw': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '7ztbb7zd': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '5k3maxgv': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'hilwrd84': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '8wa8dc97': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'hlkotqx2': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '5wkzee24': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '31lfef1e': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'qcmezt7g': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'o2zwpyto': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '4f0sx62l': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'pdo5ovag': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // profile
  {
    'g7a9ubvk': {
      'en': 'Your Profile',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'y8r21px7': {
      'en': 'Below are your settings',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'lsa3dnot': {
      'en': 'Edit Profile',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'atjmsjjh': {
      'en': 'Account',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'qkrv2bbz': {
      'en': 'Switch to Dark Mode',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'mzdf244x': {
      'en': 'Switch to Light Mode',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '0pqq7woz': {
      'en': 'Country',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'oc5e0851': {
      'en': 'Edit Profile',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ufl5u4ev': {
      'en': 'General',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'yy4qns49': {
      'en': 'Support',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '4mxcp5ue': {
      'en': 'Terms of Service',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '4olua3mt': {
      'en': 'Invite Friends',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'jpn9srkz': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // signIn
  {
    'x3pjyhn2': {
      'en': 'Welcome Back!',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'xjnd69ad': {
      'en': 'Use the form below to access your account.',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ysfzvre4': {
      'en': 'Email Address',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '3fxmvps1': {
      'en': 'Enter your email here...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'kzzb2hxd': {
      'en': 'Password',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '8aegaj89': {
      'en': 'Enter your email here...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'je6bu5le': {
      'en': 'Forgot Password?',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'osbkxc8u': {
      'en': 'Sign In',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'dqsmjf9w': {
      'en': 'Use a social platform to continue',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'eqc7eq5k': {
      'en': 'Don\'t have an account?',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'hzq7uv8j': {
      'en': 'Create Account',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '2d9muoh8': {
      'en': 'Continue as Guest',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'xju1dys8': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // signUp
  {
    '0i52ikpv': {
      'en': 'Get Started',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '5a1k51jc': {
      'en': 'Create an account by using the form below.',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ilkd82j5': {
      'en': 'Email Address',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'y9b0zxkc': {
      'en': 'Enter your email here...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ekyry463': {
      'en': 'Password',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'badt9h89': {
      'en': 'Enter your email here...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'wl74m7xn': {
      'en': 'Sign Up',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'inp36tzv': {
      'en': 'Use a social platform to continue',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'sxsbbdec': {
      'en': 'Already have an account?',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'nzgwexi2': {
      'en': 'Login',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '7z0e0jir': {
      'en': 'Continue as Guest',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ztd45ex6': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // createProfile
  {
    '8t9uzheh': {
      'en': 'Create Profile',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '0utv8zgf': {
      'en': 'Your Name',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'rojigrmt': {
      'en': 'Your City',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '1xr0dexa': {
      'en': 'State',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'l7bcdecp': {
      'en': 'State',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '1a5rz8d2': {
      'en': 'Alabama',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'm5y7mz8g': {
      'en': 'Alaska',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ouuzm4mw': {
      'en': 'Arizona',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'n2kptme2': {
      'en': 'Arkansas',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'rj63afa8': {
      'en': 'California',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '4372hs22': {
      'en': 'Colorado',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'f5c69gn0': {
      'en': 'Connecticut',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ff2ecqd0': {
      'en': 'Delaware',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'uz4617iv': {
      'en': 'Florida',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'gfbk0de7': {
      'en': 'Georgia',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'rzzsnmte': {
      'en': 'Hawaii',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '5jjheo6s': {
      'en': 'Idaho',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '9xukawl3': {
      'en': 'Illinoi',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'fwrw3y19': {
      'en': 'Indiana',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'owk1p9dp': {
      'en': 'Iowa',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '2jaf5o77': {
      'en': 'Kansas',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '4f3x00uo': {
      'en': 'Kentucky',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'pkutxruf': {
      'en': 'Louisiana',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'jfe7dbtu': {
      'en': 'Maine',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'riae458m': {
      'en': 'Maryland',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'aeuqbree': {
      'en': 'Massachusetts',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'k6516rep': {
      'en': 'Michigan',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'oesjqokk': {
      'en': 'Minnesota',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '4l013y4k': {
      'en': 'Mississippi',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'n4byh7yq': {
      'en': 'Missouri',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '483zot8y': {
      'en': 'Monta',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '5dl70m25': {
      'en': 'Nebraska',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '9z6ucfxr': {
      'en': 'Nevada',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '50hu934a': {
      'en': 'New Hampshire',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'z8zc17y1': {
      'en': 'New Jersey',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '5ygdlnyz': {
      'en': 'New Mexico',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '8i88r8pa': {
      'en': 'New York',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ch493xs5': {
      'en': 'North Carolina',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'jcneqsn7': {
      'en': 'North Dak',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '1m8f0w6z': {
      'en': 'Ohio',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'vly86v6g': {
      'en': 'Oklahoma',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'xc4u6qlh': {
      'en': 'Oregon',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'vra6obac': {
      'en': 'Pennsylvani',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'i7py80jo': {
      'en': 'Rhode Island',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'u5gz507n': {
      'en': 'South Caroli',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '7w94qj9e': {
      'en': 'South Dakota',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '58e6ws1e': {
      'en': 'Tennessee',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '2ytyi7gz': {
      'en': 'Texas',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'enitnfpa': {
      'en': 'Utah',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'nwqevjxp': {
      'en': 'Vermont',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    's8xai7rl': {
      'en': 'Virginia',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '5equd54b': {
      'en': 'Washingto',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'zukuhigj': {
      'en': 'West Virginia',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'rlskah2n': {
      'en': 'Wisconsin',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'accazyf9': {
      'en': 'Wyoming',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '410hnlga': {
      'en': 'Select State',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '5dkgt7rd': {
      'en': 'Your bio',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '0pxdperx': {
      'en': 'Save Changes',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '49jcqbv0': {
      'en': 'Create Profile',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'bap0yno0': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // forgotPassword
  {
    'ua93pz1r': {
      'en': 'Forgot Password',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'n0qd59as': {
      'en':
          'We will send you an email with a link to reset your password, please enter the email associated with your account below.',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ek0la9km': {
      'en': 'Your email',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'vvnqpaym': {
      'en': 'Enter your email to recieve a linke...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'grzhkryr': {
      'en': 'Send Reset Link',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'i49gj6a1': {
      'en': 'Forgot Password',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'zt02zprv': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // phoneSignIn
  {
    'wt3wf6jf': {
      'en': 'Phone Sign In',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '540aou30': {
      'en': 'Phone Sign In',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '7uj357ej': {
      'en': 'Type in your phone number below to register.',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'i9vgdxeu': {
      'en': 'Your Phone Number',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ob0mzwjh': {
      'en': 'Please enter a valid number...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '30vrts83': {
      'en': 'Sign In with Phone',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'xwgt4fg9': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // phoneVerify
  {
    'xqlwykms': {
      'en': 'PhoneVerify',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '3h4s915g': {
      'en': 'Confirm your Code',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'dufq2fek': {
      'en': 'This code helps keep your account safe and secure.',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'itslfr93': {
      'en': 'Confirm & Continue',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'i1e34ouv': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // devices
  {
    'sq7whvd7': {
      'en': 'Your Device',
      'de': 'Ihr Gerät',
      'fr': 'Votre appareil',
      'ja': 'あなたのデバイス',
      'zh_Hans': '你的设备',
    },
    'uwf38tav': {
      'en': 'Your projects are below',
      'de': 'Ihre Projekte sind unten',
      'fr': 'Vos projets ci-dessous',
      'ja': 'あなたのプロジェクトは以下のとおりです',
      'zh_Hans': '您的项目如下',
    },
    'ung48p3m': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'g4wgai3p': {
      'en': 'Notifications',
      'de': 'Benachrichtigungen',
      'fr': 'Avis',
      'ja': '通知',
      'zh_Hans': '通知',
    },
    'ztplktp1': {
      'en': 'Below are you new notifications.',
      'de': 'Unten sind Ihre neuen Benachrichtigungen.',
      'fr': 'Vous trouverez ci-dessous de nouvelles notifications.',
      'ja': '以下は新しい通知です。',
      'zh_Hans': '以下是您的新通知。',
    },
    'iz6jrii7': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'ksez3kno': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'r2h75wh2': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'tp8x4mw9': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'touv5jw6': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'e6j0rkt6': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'gum79urz': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'oi5lwlww': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    '1hmi171e': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'wf83js02': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'j0gqvfwq': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'gkchjs66': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    '7hfv5ffv': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // mainWebNav
  {
    '21i2vb5f': {
      'en': 'DigitalFactory',
      'de': 'Platin',
      'fr': 'Platine',
      'ja': '白金',
      'zh_Hans': '铂',
    },
    'vc28a6wh': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
    'sgj7ppzr': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
    '6h03nko5': {
      'en': 'Devices',
      'de': 'Projekte',
      'fr': 'Projets',
      'ja': 'プロジェクト',
      'zh_Hans': '项目',
    },
    'sw33tlrx': {
      'en': 'ORGANIZATION',
      'de': 'ORGANISATION',
      'fr': 'ORGANISME',
      'ja': '組織',
      'zh_Hans': '组织',
    },
    'rn0xcho7': {
      'en': 'Profile',
      'de': 'Einstellungen',
      'fr': 'Réglages',
      'ja': '設定',
      'zh_Hans': '设置',
    },
    '76f2nva8': {
      'en': 'Help Center',
      'de': 'Hilfezentrum',
      'fr': 'Centre d\'aide',
      'ja': 'ヘルプセンター',
      'zh_Hans': '帮助中心',
    },
    'jn3sy1cs': {
      'en': 'Having trouble with Platinum? Contact us below.',
      'de': 'Haben Sie Probleme mit Platinum? Kontaktieren Sie uns unten.',
      'fr': 'Un problème avec Platinum ? Contactez-nous ci-dessous.',
      'ja': 'プラチナでお困りですか？下記までお問い合わせください。',
      'zh_Hans': '铂金有问题吗？请在下方联系我们。',
    },
    'pvwevd9h': {
      'en': 'Go To Help Center',
      'de': 'Gehen Sie zum Hilfecenter',
      'fr': 'Aller au centre d\'aide',
      'ja': 'ヘルプセンターに移動',
      'zh_Hans': '前往帮助中心',
    },
  },
  // mobileNav
  {
    'e3ap1bhd': {
      'en': 'Home',
      'de': 'ZUHAUSE',
      'fr': 'DOMICILE',
      'ja': '家',
      'zh_Hans': '家',
    },
    'zu0rlxg9': {
      'en': 'Devices',
      'de': 'GERÄT',
      'fr': 'APPAREIL',
      'ja': 'デバイス',
      'zh_Hans': '设备',
    },
    'anet0juh': {
      'en': 'Profile',
      'de': 'GERÄT',
      'fr': 'APPAREIL',
      'ja': 'デバイス',
      'zh_Hans': '设备',
    },
  },
  // messageBottomSheet
  {
    'ktdkqgbm': {
      'en': 'Your Messages',
      'de': 'Deine Nachrichten',
      'fr': 'Tes messages',
      'ja': 'あなたのメッセージ',
      'zh_Hans': '您的讯息',
    },
    '2il0e6ew': {
      'en': 'Below are your new messages',
      'de': 'Unten sind Ihre neuen Nachrichten',
      'fr': 'Ci-dessous vos nouveaux messages',
      'ja': '以下はあなたの新しいメッセージです',
      'zh_Hans': '以下是您的新消息',
    },
    'hlk121nf': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '23b20gjc': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'xacpnb09': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'modh842x': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    '1j0k11dd': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'c3e4q9x4': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'l62ds5ok': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'pqs5d09o': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'qidychpf': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '1ijny0po': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'c5x0vktf': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    '686d70vz': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
  },
  // altNav
  {
    'h834rd3x': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
    'i0qrdyp0': {
      'en': 'DigitalFacotry',
      'de': 'Platin',
      'fr': 'Platine',
      'ja': '白金',
      'zh_Hans': '铂',
    },
    'mg2878en': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
    'fwr96f9a': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
    'b86hxizm': {
      'en': 'Devices',
      'de': 'Projekte',
      'fr': 'Projets',
      'ja': 'プロジェクト',
      'zh_Hans': '项目',
    },
    '55h9ooma': {
      'en': 'ORGANIZATION',
      'de': 'ORGANISATION',
      'fr': 'ORGANISME',
      'ja': '組織',
      'zh_Hans': '组织',
    },
    'vi5wq5d3': {
      'en': 'Profile',
      'de': 'Abrechnung',
      'fr': 'Facturation',
      'ja': '請求する',
      'zh_Hans': '计费',
    },
  },
  // altNav_2
  {
    'bpjevkz3': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
  },
  // deviceListItem
  {
    'eyv2tlvc': {
      'en': 'Today amount',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // Miscellaneous
  {
    'kvg9m1kb': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '7w4brihj': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'npbs0pmg': {
      'en': 'Need allow access your contacts',
      'de': 'Sie müssen den Zugriff auf Ihre Kontakte zulassen',
      'fr': 'Besoin d\'autoriser l\'accès à vos contacts',
      'ja': '連絡先へのアクセスを許可する必要があります',
      'zh_Hans': '需要允许访问您的联系人',
    },
    'efnuksla': {
      'en': 'Need allow access your camera',
      'de': 'Sie müssen den Zugriff auf Ihre Kamera zulassen',
      'fr': 'Besoin d\'autoriser l\'accès à votre caméra',
      'ja': 'カメラへのアクセスを許可する必要があります',
      'zh_Hans': '需要允许访问您的相机',
    },
    'mzj4qkwt': {
      'en': 'Need allow receive notifications',
      'de': 'Sie müssen Benachrichtigungen zulassen',
      'fr': 'Besoin d\'autoriser la réception de notifications',
      'ja': '通知の受信を許可する必要があります',
      'zh_Hans': '需要允许接收通知',
    },
    'y6f1ynia': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'wj5s1man': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '3yoybylu': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'i6mqa42t': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'fmtdapq7': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'oxwdmxuv': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '9tdv712t': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '0q37v7ae': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'l8plm2qe': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'k0p03qqc': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'k1pao2q1': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '2xbikfwk': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '8d1vbej9': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'sdj9y57r': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'x6ibyxcy': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'lyu9nw9g': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    's7c8j8a2': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'nikufej9': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ntuttike': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    's253iup4': {
      'en': '',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // deviceInfo
  {
    'gckhg94l': {
      'en': 'Device Info',
      'de': 'Geräteinformationen',
      'fr': 'Info appareil',
      'ja': '機器情報',
      'zh_Hans': '设备信息',
    },
    'h6ud908v': {
      'en': 'Utilization rate',
      'de': 'Nutzungsrate',
      'fr': "Taux d'utilisation",
      'ja': '稼働率',
      'zh_Hans': '稼动率',
    },
    'tkjsv50t': {
      'en': 'Speed',
      'de': 'Geschwindigkeit',
      'fr': 'Vitesse',
      'ja': 'スピード',
      'zh_Hans': '速度',
    },
    '0wi8tqjp': {
      'en': 'Status',
      'de': 'Status',
      'fr': 'Statut',
      'ja': '状態',
      'zh_Hans': '状态',
    },
    'y9gfrnf7': {
      'en': 'DigitalFatory',
      'de': 'DigitalFatory',
      'fr': 'DigitalFatory',
      'ja': 'DigitalFatory',
      'zh_Hans': 'DigitalFatory',
    },
    'u13gq2ru': {
      'en': '4:30pm',
      'de': '4:30pm',
      'fr': '4:30pm',
      'ja': '4:30pm',
      'zh_Hans': '4:30pm',
    },
    '2rrlmpwm': {
      'en': 'device occuring problem.',
      'de': 'Geräteproblem.',
      'fr': "problème d'apparition de l'appareil.",
      'ja': 'デバイスに発生する問題。',
      'zh_Hans': '设备出现问题。',
    }
  },
].reduce((a, b) => a..addAll(b));
