import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'zh_Hans', 'ja', 'fr', 'de'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? zh_HansText = '',
    String? jaText = '',
    String? frText = '',
    String? deText = '',
  }) =>
      [enText, zh_HansText, jaText, frText, deText][languageIndex] ?? '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'byoctihc': {
      'en': 'Welcome to DigitalFactory',
      'de': 'Willkommen bei DigitalFactory',
      'fr': 'Bienvenue sur DigitalFactory',
      'ja': 'デジタルファクトリーへようこそ',
      'zh_Hans': '欢迎来到数字工厂',
    },
    '7m5o70u8': {
      'en': 'Hello Guest! Welcome back.',
      'de': 'Hallo Gast! Willkommen zurück.',
      'fr': 'Bonjour Invité ! Content de te revoir.',
      'ja': 'こんにちはゲスト！おかえり。',
      'zh_Hans': '客人您好！欢迎回来。',
    },
    'qbhcr7z8': {
      'en': 'Create',
      'de': 'Schaffen',
      'fr': 'Créer',
      'ja': '作成',
      'zh_Hans': '创造',
    },
    '8dok0sfa': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'hmzlh35e': {
      'en': 'OVERVIEW',
      'de': 'ÜBERBLICK',
      'fr': 'APERÇU',
      'ja': '概要',
      'zh_Hans': '概述',
    },
    'gh6q6yoe': {
      'en': 'TOTAL OUTPUT',
      'de': 'GESAMTLEISTUNG',
      'fr': 'SORTIE TOTALE',
      'ja': '総生産高',
      'zh_Hans': '总产出',
    },
    'saf5ng86': {
      'en': '500.20B',
      'de': '500.20B',
      'fr': '500.20B',
      'ja': '500.20B',
      'zh_Hans': '500.20B',
    },
    '21x8wjwg': {
      'en': 'AVG EFFICENCY',
      'de': 'DURCHSCHNITTLICHE EFFIZIENZ',
      'fr': 'EFFICACITÉ MOYENNE',
      'ja': '平均効率',
      'zh_Hans': '平均效率',
    },
    'nilobwjj': {
      'en': '95.76%',
      'de': '95,76 %',
      'fr': '95,76 %',
      'ja': '95.76%',
      'zh_Hans': '95.76%',
    },
    '10re4v7b': {
      'en': 'OUTPUT TODAY',
      'de': 'AUSGABE HEUTE',
      'fr': 'SORTIE AUJOURD\'HUI',
      'ja': '今日のアウトプット',
      'zh_Hans': '今天的产量',
    },
    'arnt20hm': {
      'en': '0.25M',
      'de': '0,25 M',
      'fr': '0.25M',
      'ja': '0.25M',
      'zh_Hans': '0.25M',
    },
    'sgyjfrph': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    '4vnhjwga': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    'i3pymgyw': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    'ven1qpwz': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    'j2pwgghh': {
      'en': 'Recent Transactions',
      'de': 'kürzliche Transaktionen',
      'fr': 'transactions récentes',
      'ja': '最近の取引',
      'zh_Hans': '最近的交易',
    },
    'x3bosezi': {
      'en': 'A list of all your transactions this week.',
      'de': 'Eine Liste all Ihrer Transaktionen in dieser Woche.',
      'fr': 'Une liste de toutes vos transactions cette semaine.',
      'ja': '今週のすべての取引のリスト。',
      'zh_Hans': '本周所有交易的清单。',
    },
    'ugexvbho': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '4sj6q249': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'g4q7em13': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'uyez15e0': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'g8lm8mmf': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'zfq2nr46': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'vswdglna': {
      'en': 'Mon, 4',
      'de': 'Mo, 4',
      'fr': 'lun, 4',
      'ja': '4月',
      'zh_Hans': '周一，4',
    },
    '8m2u21ii': {
      'en': 'Date',
      'de': 'Datum',
      'fr': 'Date',
      'ja': '日にち',
      'zh_Hans': '日期',
    },
    'gyqmfzpj': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'foucb0tm': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '6flytqn1': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'd2nr9orx': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'ikhk2l97': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'ipmv5p5p': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '06fmgbx1': {
      'en': 'Thu, 9',
      'de': 'Do, 9',
      'fr': 'jeu., 9',
      'ja': '9日(木)',
      'zh_Hans': '周四，9',
    },
    'okhw972o': {
      'en': 'Date',
      'de': 'Datum',
      'fr': 'Date',
      'ja': '日にち',
      'zh_Hans': '日期',
    },
    'zgvfsj1c': {
      'en': 'Notifications',
      'de': 'Benachrichtigungen',
      'fr': 'Avis',
      'ja': '通知',
      'zh_Hans': '通知',
    },
    'vi2nyjjh': {
      'en': 'Below are you new notifications.',
      'de': 'Unten sind Ihre neuen Benachrichtigungen.',
      'fr': 'Vous trouverez ci-dessous de nouvelles notifications.',
      'ja': '以下は新しい通知です。',
      'zh_Hans': '以下是您的新通知。',
    },
    'w20qzy9r': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'cunsd5z0': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'e2vfwyui': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'gw7j3ise': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'j1uzjil0': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'vww8fm3v': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'vrl92nk0': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'ypwg6dnl': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    '3gcwkub9': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'qjifeynz': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'qo1r6531': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'gxsnut94': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'y3jglg7t': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // projects
  {
    'vibf8vqe': {
      'en': 'Your Device',
      'de': 'Ihr Gerät',
      'fr': 'Votre appareil',
      'ja': 'あなたのデバイス',
      'zh_Hans': '你的设备',
    },
    'wqd27t6p': {
      'en': 'Your projects are below',
      'de': 'Ihre Projekte sind unten',
      'fr': 'Vos projets ci-dessous',
      'ja': 'あなたのプロジェクトは以下のとおりです',
      'zh_Hans': '您的项目如下',
    },
    'cthhf2m6': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'z68t3rnq': {
      'en': 'Recent Projects',
      'de': 'Letzte Projekte',
      'fr': 'les projets récents',
      'ja': '最近のプロジェクト',
      'zh_Hans': '最近的项目',
    },
    'h1ay9ycl': {
      'en': 'A list of all your transactions this week.',
      'de': 'Eine Liste all Ihrer Transaktionen in dieser Woche.',
      'fr': 'Une liste de toutes vos transactions cette semaine.',
      'ja': '今週のすべての取引のリスト。',
      'zh_Hans': '本周所有交易的清单。',
    },
    'j3qde5su': {
      'en': 'Medical App',
      'de': 'Medizinische App',
      'fr': 'Application médicale',
      'ja': '医療アプリ',
      'zh_Hans': '医疗应用',
    },
    'pxpgqwdc': {
      'en': 'Project Name',
      'de': 'Projektname',
      'fr': 'nom du projet',
      'ja': 'プロジェクト名',
      'zh_Hans': '项目名称',
    },
    '3z7nmr6f': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '9bhn24mr': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'idzmu2wi': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '54mfzudv': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'fc3l4cci': {
      'en': 'Insurance Calculator',
      'de': 'Versicherungsrechner',
      'fr': 'Calculateur d\'assurance',
      'ja': '保険計算機',
      'zh_Hans': '保险计算器',
    },
    'my72mqq9': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '2ulr89n7': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'hp2y9i8r': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'zzx573ee': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'edxgn93j': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'j2s3k37r': {
      'en': 'Team Tutorials',
      'de': 'Team-Tutorials',
      'fr': 'Tutoriels d\'équipe',
      'ja': 'チーム チュートリアル',
      'zh_Hans': '团队教程',
    },
    'qoxj42m8': {
      'en': 'The latest tutorials posted by your team.',
      'de': 'Die neuesten Tutorials, die von Ihrem Team gepostet wurden.',
      'fr': 'Les derniers tutos postés par votre équipe.',
      'ja': 'チームが投稿した最新のチュートリアル。',
      'zh_Hans': '您的团队发布的最新教程。',
    },
    'l4bewi5m': {
      'en': '05:03',
      'de': '05:03',
      'fr': '05:03',
      'ja': '05:03',
      'zh_Hans': '05:03',
    },
    'z4iyjsj2': {
      'en': '1.Sketch and userflows within your application',
      'de': '1.Sketch und Userflows innerhalb Ihrer Anwendung',
      'fr': '1.Sketch et flux d\'utilisateurs au sein de votre application',
      'ja': '1.アプリケーション内のスケッチとユーザーフロー',
      'zh_Hans': '1.应用程序中的 Sketch 和用户流程',
    },
    'pq237ho6': {
      'en':
          'Sketch and userflows within your application are an important part of any problem! We go over the common use cases in order to not make rookie mistakes.',
      'de':
          'Skizzen und Benutzerabläufe innerhalb Ihrer Anwendung sind ein wichtiger Teil jedes Problems! Wir gehen die üblichen Anwendungsfälle durch, um keine Anfängerfehler zu machen.',
      'fr':
          'Les croquis et les flux d\'utilisateurs au sein de votre application sont une partie importante de tout problème ! Nous passons en revue les cas d\'utilisation courants afin de ne pas commettre d\'erreurs de débutant.',
      'ja':
          'アプリケーション内のスケッチとユーザーフローは、あらゆる問題の重要な部分です!初歩的なミスをしないように、一般的なユースケースについて説明します。',
      'zh_Hans': '应用程序中的草图和用户流是任何问题的重要组成部分！为了不犯菜鸟错误，我们回顾了常见的用例。',
    },
    '4abyu1jx': {
      'en': 'Download',
      'de': 'Download',
      'fr': 'Télécharger',
      'ja': 'ダウンロード',
      'zh_Hans': '下载',
    },
    'ebq9re0v': {
      'en': '05:03',
      'de': '05:03',
      'fr': '05:03',
      'ja': '05:03',
      'zh_Hans': '05:03',
    },
    'scz4szsz': {
      'en': '1.Sketch and userflows within your application',
      'de': '1.Sketch und Userflows innerhalb Ihrer Anwendung',
      'fr': '1.Sketch et flux d\'utilisateurs au sein de votre application',
      'ja': '1.アプリケーション内のスケッチとユーザーフロー',
      'zh_Hans': '1.应用程序中的 Sketch 和用户流程',
    },
    'v4hwlc6i': {
      'en':
          'Sketch and userflows within your application are an important part of any problem! We go over the common use cases in order to not make rookie mistakes.',
      'de':
          'Skizzen und Benutzerabläufe innerhalb Ihrer Anwendung sind ein wichtiger Teil jedes Problems! Wir gehen die üblichen Anwendungsfälle durch, um keine Anfängerfehler zu machen.',
      'fr':
          'Les croquis et les flux d\'utilisateurs au sein de votre application sont une partie importante de tout problème ! Nous passons en revue les cas d\'utilisation courants afin de ne pas commettre d\'erreurs de débutant.',
      'ja':
          'アプリケーション内のスケッチとユーザーフローは、あらゆる問題の重要な部分です!初歩的なミスをしないように、一般的なユースケースについて説明します。',
      'zh_Hans': '应用程序中的草图和用户流是任何问题的重要组成部分！为了不犯菜鸟错误，我们回顾了常见的用例。',
    },
    'k8kv6do5': {
      'en': 'Download',
      'de': 'Download',
      'fr': 'Télécharger',
      'ja': 'ダウンロード',
      'zh_Hans': '下载',
    },
    'qchxadb7': {
      'en': '05:03',
      'de': '05:03',
      'fr': '05:03',
      'ja': '05:03',
      'zh_Hans': '05:03',
    },
    'od2otrh7': {
      'en': '1.Sketch and userflows within your application',
      'de': '1.Sketch und Userflows innerhalb Ihrer Anwendung',
      'fr': '1.Sketch et flux d\'utilisateurs au sein de votre application',
      'ja': '1.アプリケーション内のスケッチとユーザーフロー',
      'zh_Hans': '1.应用程序中的 Sketch 和用户流程',
    },
    '818gl66h': {
      'en':
          'Sketch and userflows within your application are an important part of any problem! We go over the common use cases in order to not make rookie mistakes.',
      'de':
          'Skizzen und Benutzerabläufe innerhalb Ihrer Anwendung sind ein wichtiger Teil jedes Problems! Wir gehen die üblichen Anwendungsfälle durch, um keine Anfängerfehler zu machen.',
      'fr':
          'Les croquis et les flux d\'utilisateurs au sein de votre application sont une partie importante de tout problème ! Nous passons en revue les cas d\'utilisation courants afin de ne pas commettre d\'erreurs de débutant.',
      'ja':
          'アプリケーション内のスケッチとユーザーフローは、あらゆる問題の重要な部分です!初歩的なミスをしないように、一般的なユースケースについて説明します。',
      'zh_Hans': '应用程序中的草图和用户流是任何问题的重要组成部分！为了不犯菜鸟错误，我们回顾了常见的用例。',
    },
    'zoktxtin': {
      'en': 'Download',
      'de': 'Download',
      'fr': 'Télécharger',
      'ja': 'ダウンロード',
      'zh_Hans': '下载',
    },
    'wl92yxg8': {
      'en': 'Notifications',
      'de': 'Benachrichtigungen',
      'fr': 'Avis',
      'ja': '通知',
      'zh_Hans': '通知',
    },
    '88ighwvg': {
      'en': 'Below are you new notifications.',
      'de': 'Unten sind Ihre neuen Benachrichtigungen.',
      'fr': 'Vous trouverez ci-dessous de nouvelles notifications.',
      'ja': '以下は新しい通知です。',
      'zh_Hans': '以下是您的新通知。',
    },
    'dow75c37': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'imvp4zoh': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'yg0bk3bt': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'x42j95vy': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'zp6iay4z': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'ydsh35x3': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'pgfbshj3': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'x3mgsj5a': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'qu81rf0d': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '6yl6afsi': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'ohgm7pn6': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'yvgap105': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'ryjm6uw3': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // teamMembers
  {
    'p4rq490b': {
      'en': '团队成员',
      'de': '团队成员',
      'fr': '团队成员',
      'ja': '团队成员',
      'zh_Hans': '团队成员',
    },
    'rztx28ul': {
      'en': '管理您的团队成员.',
      'de': '管理您的团队成员.',
      'fr': '管理您的团队成员.',
      'ja': '管理您的团队成员.',
      'zh_Hans': '管理您的团队成员。',
    },
    '8ujiwi43': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'z8mfbfn6': {
      'en': '成员姓名',
      'de': '成员姓名',
      'fr': '成员姓名',
      'ja': '成员姓',
      'zh_Hans': '成员姓名',
    },
    '331dnrwl': {
      'en': 'Email',
      'de': 'Email',
      'fr': 'E-mail',
      'ja': 'Eメール',
      'zh_Hans': '电子邮件',
    },
    '416wkor8': {
      'en': 'Last Active',
      'de': 'letzte Aktivität',
      'fr': 'Dernier actif',
      'ja': '最後にログインした時',
      'zh_Hans': '最后登录',
    },
    '1jl7kmi7': {
      'en': 'Date Created',
      'de': 'Datum erstellt',
      'fr': 'date créée',
      'ja': '作成日',
      'zh_Hans': '创建日期',
    },
    'mxkdnaka': {
      'en': '状态',
      'de': '状态',
      'fr': '状态',
      'ja': '状態态',
      'zh_Hans': '状态',
    },
    'rpv8c4fn': {
      'en': 'Custom Name',
      'de': 'Benutzerdefinierter Name',
      'fr': 'Nom d\'usage',
      'ja': 'カスタム名',
      'zh_Hans': '自定义名称',
    },
    '2vwdezwn': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    '48gda6wk': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'svzx0i57': {
      'en': 'Active',
      'de': 'Aktiv',
      'fr': 'Actif',
      'ja': 'アクティブ',
      'zh_Hans': '积极的',
    },
    '899v004e': {
      'en': 'Custom Name',
      'de': 'Benutzerdefinierter Name',
      'fr': 'Nom d\'usage',
      'ja': 'カスタム名',
      'zh_Hans': '自定义名称',
    },
    'e7vbdfis': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'c6seagt0': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'ssljt50j': {
      'en': 'Active',
      'de': 'Aktiv',
      'fr': 'Actif',
      'ja': 'アクティブ',
      'zh_Hans': '积极的',
    },
    'jth741bx': {
      'en': 'Custom Name',
      'de': 'Benutzerdefinierter Name',
      'fr': 'Nom d\'usage',
      'ja': 'カスタム名',
      'zh_Hans': '自定义名称',
    },
    '8y7yljvw': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    '9bhrw6tn': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'cgyt2sru': {
      'en': 'Active',
      'de': 'Aktiv',
      'fr': 'Actif',
      'ja': 'アクティブ',
      'zh_Hans': '积极的',
    },
    'k9u458xy': {
      'en': 'Custom Name',
      'de': 'Benutzerdefinierter Name',
      'fr': 'Nom d\'usage',
      'ja': 'カスタム名',
      'zh_Hans': '自定义名称',
    },
    '405q5jfr': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'y2oct28i': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'gkwpxlxl': {
      'en': 'Active',
      'de': 'Aktiv',
      'fr': 'Actif',
      'ja': 'アクティブ',
      'zh_Hans': '积极的',
    },
    'r2hntndi': {
      'en': 'Custom Name',
      'de': 'Benutzerdefinierter Name',
      'fr': 'Nom d\'usage',
      'ja': 'カスタム名',
      'zh_Hans': '自定义名称',
    },
    '8zkeyoic': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'we6orzp3': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'ixon91s3': {
      'en': 'Active',
      'de': 'Aktiv',
      'fr': 'Actif',
      'ja': 'アクティブ',
      'zh_Hans': '积极的',
    },
    'a1uppq73': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // billing
  {
    'vdqn0f0z': {
      'en': 'Billing',
      'de': 'Abrechnung',
      'fr': 'Facturation',
      'ja': '請求する',
      'zh_Hans': '计费',
    },
    '8e9a31jj': {
      'en': 'Please check the latest payments and your balance below.',
      'de':
          'Bitte überprüfen Sie die letzten Zahlungen und Ihr Guthaben unten.',
      'fr':
          'Veuillez vérifier les derniers paiements et votre solde ci-dessous.',
      'ja': '最新の支払いと残高を以下で確認してください。',
      'zh_Hans': '请在下方查看最近的付款和您的余额。',
    },
    '91lcng77': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'ehr6pm5q': {
      'en': 'Money In',
      'de': 'Geld rein',
      'fr': 'Argent entrant',
      'ja': '入金額',
      'zh_Hans': '入金',
    },
    '1tqjh5mc': {
      'en': 'The amount of money received this month.',
      'de': 'Der Geldbetrag, den Sie diesen Monat erhalten haben.',
      'fr': 'Le montant d\'argent reçu ce mois-ci.',
      'ja': '今月受け取った金額。',
      'zh_Hans': '本月收到的金额。',
    },
    'ci4s2s8h': {
      'en': '\$3,502',
      'de': '3.502 \$',
      'fr': '3 502 \$',
      'ja': '\$3,502',
      'zh_Hans': '3,502 美元',
    },
    'dcp802no': {
      'en': 'Money Out',
      'de': 'Geld aus',
      'fr': 'Plus d\'argent',
      'ja': 'マネーアウト',
      'zh_Hans': '出钱',
    },
    'nnkd0mf7': {
      'en': 'The amount you paid this month.',
      'de': 'Der Betrag, den Sie diesen Monat bezahlt haben.',
      'fr': 'Le montant que vous avez payé ce mois-ci.',
      'ja': '今月支払った金額。',
      'zh_Hans': '您本月支付的金额。',
    },
    'f2j0plyj': {
      'en': '-\$2,201',
      'de': '-2.201 \$',
      'fr': '-\$2,201',
      'ja': '-\$2,201',
      'zh_Hans': '- 2,201 美元',
    },
    'dr3ck58j': {
      'en': 'Current Balance',
      'de': 'Aktuelles Guthaben',
      'fr': 'Solde actuel',
      'ja': '経常収支',
      'zh_Hans': '当前余额',
    },
    'k7hz9qn0': {
      'en': 'The amount of money received this month.',
      'de': 'Der Geldbetrag, den Sie diesen Monat erhalten haben.',
      'fr': 'Le montant d\'argent reçu ce mois-ci.',
      'ja': '今月受け取った金額。',
      'zh_Hans': '本月收到的金额。',
    },
    'hvenv1kh': {
      'en': '\$42,592',
      'de': '42.592 \$',
      'fr': '42 592 \$',
      'ja': '\$42,592',
      'zh_Hans': '42,592 美元',
    },
    'bu72h4fn': {
      'en': 'Payment Name',
      'de': 'Zahlungsname',
      'fr': 'Nom du paiement',
      'ja': 'お支払い名',
      'zh_Hans': '付款名称',
    },
    's8b75ywh': {
      'en': 'Paid by',
      'de': 'Bezahlt von',
      'fr': 'Payé par',
      'ja': 'によって支払われました',
      'zh_Hans': '由...支付',
    },
    '7wvqrrgo': {
      'en': 'Paid on',
      'de': 'Bezahlt am',
      'fr': 'Payé le',
      'ja': '支払い済み',
      'zh_Hans': '支付于',
    },
    '9798g27r': {
      'en': 'Amount',
      'de': 'Menge',
      'fr': 'Quantité',
      'ja': '額',
      'zh_Hans': '数量',
    },
    'wjdmz2p6': {
      'en': 'Subscription Billing',
      'de': 'Abonnement-Abrechnung',
      'fr': 'Facturation de l\'abonnement',
      'ja': 'サブスクリプション請求',
      'zh_Hans': '订阅计费',
    },
    '4g9qursh': {
      'en': 'Andrew D.',
      'de': 'Andreas D.',
      'fr': 'André D.',
      'ja': 'アンドリュー・D.',
      'zh_Hans': '安德鲁·D。',
    },
    'xckko3o1': {
      'en': 'Aug. 8, 2022',
      'de': '8. August 2022',
      'fr': '8 août 2022',
      'ja': '2022年8月8日',
      'zh_Hans': '2022 年 8 月 8 日',
    },
    '9q4m59kd': {
      'en': '\$199.99',
      'de': '199,99 \$',
      'fr': '199,99 \$',
      'ja': '\$199.99',
      'zh_Hans': '199.99 美元',
    },
    'ttlzs8z5': {
      'en': 'Subscription Billing',
      'de': 'Abonnement-Abrechnung',
      'fr': 'Facturation de l\'abonnement',
      'ja': 'サブスクリプション請求',
      'zh_Hans': '订阅计费',
    },
    '64k7g8oj': {
      'en': 'Andrew D.',
      'de': 'Andreas D.',
      'fr': 'André D.',
      'ja': 'アンドリュー・D.',
      'zh_Hans': '安德鲁·D。',
    },
    '9w547m1a': {
      'en': 'Jul. 8, 2022',
      'de': '8. Juli 2022',
      'fr': '8 juillet 2022',
      'ja': '2022年7月8日',
      'zh_Hans': '2022 年 7 月 8 日',
    },
    'mqb3xyn8': {
      'en': '\$199.99',
      'de': '199,99 \$',
      'fr': '199,99 \$',
      'ja': '\$199.99',
      'zh_Hans': '199.99 美元',
    },
    'zt7gs95g': {
      'en': 'Subscription Billing',
      'de': 'Abonnement-Abrechnung',
      'fr': 'Facturation de l\'abonnement',
      'ja': 'サブスクリプション請求',
      'zh_Hans': '订阅计费',
    },
    'd6ky0gd2': {
      'en': 'Andrew D.',
      'de': 'Andreas D.',
      'fr': 'André D.',
      'ja': 'アンドリュー・D.',
      'zh_Hans': '安德鲁·D。',
    },
    '9jarjv14': {
      'en': 'Jun. 8, 2022',
      'de': '8. Juni 2022',
      'fr': '8 juin 2022',
      'ja': '2022年6月8日',
      'zh_Hans': '2022 年 6 月 8 日',
    },
    'w5kza49v': {
      'en': '\$199.99',
      'de': '199,99 \$',
      'fr': '199,99 \$',
      'ja': '\$199.99',
      'zh_Hans': '199.99 美元',
    },
    'plbqsr0i': {
      'en': 'Subscription Billing',
      'de': 'Abonnement-Abrechnung',
      'fr': 'Facturation de l\'abonnement',
      'ja': 'サブスクリプション請求',
      'zh_Hans': '订阅计费',
    },
    'uj47c0ro': {
      'en': 'Andrew D.',
      'de': 'Andreas D.',
      'fr': 'André D.',
      'ja': 'アンドリュー・D.',
      'zh_Hans': '安德鲁·D。',
    },
    'wjv3xcmr': {
      'en': 'May 8, 2022',
      'de': '8. Mai 2022',
      'fr': '8 mai 2022',
      'ja': '2022 年 5 月 8 日',
      'zh_Hans': '2022 年 5 月 8 日',
    },
    '8emjk1w6': {
      'en': '\$199.99',
      'de': '199,99 \$',
      'fr': '199,99 \$',
      'ja': '\$199.99',
      'zh_Hans': '199.99 美元',
    },
    '0yz5mznc': {
      'en': 'Subscription Billing',
      'de': 'Abonnement-Abrechnung',
      'fr': 'Facturation de l\'abonnement',
      'ja': 'サブスクリプション請求',
      'zh_Hans': '订阅计费',
    },
    '1459tace': {
      'en': 'Andrew D.',
      'de': 'Andreas D.',
      'fr': 'André D.',
      'ja': 'アンドリュー・D.',
      'zh_Hans': '安德鲁·D。',
    },
    'x50snwgn': {
      'en': 'Apr. 8, 2022',
      'de': '8. April 2022',
      'fr': '8 avril 2022',
      'ja': '2022年4月8日',
      'zh_Hans': '2022 年 4 月 8 日',
    },
    'fr6yujwv': {
      'en': '\$199.99',
      'de': '199,99 \$',
      'fr': '199,99 \$',
      'ja': '\$199.99',
      'zh_Hans': '199.99 美元',
    },
    'obspv8hw': {
      'en': 'Subscription Billing',
      'de': 'Abonnement-Abrechnung',
      'fr': 'Facturation de l\'abonnement',
      'ja': 'サブスクリプション請求',
      'zh_Hans': '订阅计费',
    },
    'vxznvh5r': {
      'en': 'Andrew D.',
      'de': 'Andreas D.',
      'fr': 'André D.',
      'ja': 'アンドリュー・D.',
      'zh_Hans': '安德鲁·D。',
    },
    'vxa1hj3k': {
      'en': 'Mar. 8, 2022',
      'de': '8. März 2022',
      'fr': '8 mars 2022',
      'ja': '2022年3月8日',
      'zh_Hans': '2022 年 3 月 8 日',
    },
    'j3ela4da': {
      'en': '\$199.99',
      'de': '199,99 \$',
      'fr': '199,99 \$',
      'ja': '\$199.99',
      'zh_Hans': '199.99 美元',
    },
    'h4523wei': {
      'en': 'Subscription Billing',
      'de': 'Abonnement-Abrechnung',
      'fr': 'Facturation de l\'abonnement',
      'ja': 'サブスクリプション請求',
      'zh_Hans': '订阅计费',
    },
    'g2rfl4pv': {
      'en': 'Andrew D.',
      'de': 'Andreas D.',
      'fr': 'André D.',
      'ja': 'アンドリュー・D.',
      'zh_Hans': '安德鲁·D。',
    },
    '3knns36e': {
      'en': 'Feb. 8, 2022',
      'de': '8. Februar 2022',
      'fr': '8 février 2022',
      'ja': '2022年2月8日',
      'zh_Hans': '2022 年 2 月 8 日',
    },
    'sh65lqo8': {
      'en': '\$199.99',
      'de': '199,99 \$',
      'fr': '199,99 \$',
      'ja': '\$199.99',
      'zh_Hans': '199.99 美元',
    },
    'qlq4nta9': {
      'en': 'Notifications',
      'de': 'Benachrichtigungen',
      'fr': 'Avis',
      'ja': '通知',
      'zh_Hans': '通知',
    },
    'ebqnuwo7': {
      'en': 'Below are you new notifications.',
      'de': 'Unten sind Ihre neuen Benachrichtigungen.',
      'fr': 'Vous trouverez ci-dessous de nouvelles notifications.',
      'ja': '以下は新しい通知です。',
      'zh_Hans': '以下是您的新通知。',
    },
    'fgf7vn62': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'iyed1q94': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    't7qlt29p': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'z3x8byp2': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'pkd5ivyu': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'v9ubiyt9': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    '5olkyox2': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'yb11222n': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    '0ocwsowk': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'uia3kjnd': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'q9r5egv2': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    '00xiz67i': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'c1mlguce': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // responsiveTest
  {
    'cbhgiwm8': {
      'en': 'Your Projects',
      'de': 'Ihre Projekte',
      'fr': 'Tes projets',
      'ja': 'あなたのプロジェクト',
      'zh_Hans': '您的项目',
    },
    '0sls6kw7': {
      'en': 'Your projects are below, check it out.',
      'de': 'Ihre Projekte sind unten, sehen Sie es sich an.',
      'fr': 'Vos projets sont ci-dessous, consultez-les.',
      'ja': 'あなたのプロジェクトは以下にあります。チェックしてください。',
      'zh_Hans': '你的项目在下面，检查一下。',
    },
    '53zys4hr': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'tvwlt2ke': {
      'en': 'Credit Card',
      'de': 'Kreditkarte',
      'fr': 'Carte de crédit',
      'ja': 'クレジットカード',
      'zh_Hans': '信用卡',
    },
    '2w8mpf1g': {
      'en': 'Budget',
      'de': 'Budget',
      'fr': 'Budget',
      'ja': 'バジェット',
      'zh_Hans': '预算',
    },
    '1m15wkzq': {
      'en': 'Balance',
      'de': 'Balance',
      'fr': 'Solde',
      'ja': 'バランス',
      'zh_Hans': '平衡',
    },
    'c871wtzn': {
      'en': '\$7,630',
      'de': '\$7.630',
      'fr': '7 630 \$',
      'ja': '\$7,630',
      'zh_Hans': '\$7,630',
    },
    'dasfz3nr': {
      'en': '**** 0149',
      'de': '**** 0149',
      'fr': '**** 0149',
      'ja': '**** 0149',
      'zh_Hans': '**** 0149',
    },
    'zdy0xzhd': {
      'en': '05/25',
      'de': '25.05',
      'fr': '25/05',
      'ja': '05/25',
      'zh_Hans': '05/25',
    },
    'o0491zf3': {
      'en': 'Spending',
      'de': 'Ausgaben',
      'fr': 'Dépenses',
      'ja': '支出',
      'zh_Hans': '开支',
    },
    'l7olqxp3': {
      'en': 'Tab View 2',
      'de': 'Registerkartenansicht 2',
      'fr': 'Onglet Affichage 2',
      'ja': 'タブ ビュー 2',
      'zh_Hans': '选项卡视图 2',
    },
    'v68aozff': {
      'en': 'Balance',
      'de': 'Balance',
      'fr': 'Solde',
      'ja': 'バランス',
      'zh_Hans': '平衡',
    },
    'thih5h3p': {
      'en': 'Avg. Spend',
      'de': 'Durchschn. Ausgeben',
      'fr': 'Moy. Passer',
      'ja': '平均払う',
      'zh_Hans': '平均。花费',
    },
    't4di97cf': {
      'en': '\$25,205',
      'de': '25.205 \$',
      'fr': '25 205 \$',
      'ja': '\$25,205',
      'zh_Hans': '25,205 美元',
    },
    'gk4ap4gt': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    '2msyutna': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    'pmfnbk4l': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    'zzw80byt': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    '51d9zxo7': {
      'en': 'Recent Transactions',
      'de': 'kürzliche Transaktionen',
      'fr': 'transactions récentes',
      'ja': '最近の取引',
      'zh_Hans': '最近的交易',
    },
    'qqt7nhgo': {
      'en': 'A list of all your transactions this week.',
      'de': 'Eine Liste all Ihrer Transaktionen in dieser Woche.',
      'fr': 'Une liste de toutes vos transactions cette semaine.',
      'ja': '今週のすべての取引のリスト。',
      'zh_Hans': '本周所有交易的清单。',
    },
    'zget5n63': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '1p9sfg9v': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'aznzw4f3': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '4ez6kftz': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'uht4kun8': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'z30jzbsw': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '7ztbb7zd': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '5k3maxgv': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'hilwrd84': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '8wa8dc97': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'hlkotqx2': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '5wkzee24': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '31lfef1e': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'qcmezt7g': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'o2zwpyto': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '4f0sx62l': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'pdo5ovag': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // teamMembersClients
  {
    'o25rvykx': {
      'en': 'Clients',
      'de': 'Kunden',
      'fr': 'Clients',
      'ja': 'クライアント',
      'zh_Hans': '客户',
    },
    'tpwmwllz': {
      'en': 'Manage your team below.',
      'de': 'Verwalten Sie unten Ihr Team.',
      'fr': 'Gérez votre équipe ci-dessous.',
      'ja': '以下でチームを管理します。',
      'zh_Hans': '在下方管理您的团队。',
    },
    '1hzad2s6': {
      'en': 'Create',
      'de': 'Schaffen',
      'fr': 'Créer',
      'ja': '作成',
      'zh_Hans': '创造',
    },
    'n2wq0uiv': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'e7d9gpzc': {
      'en': 'Member Name',
      'de': 'Mitgliedsname',
      'fr': 'Nom de membre',
      'ja': 'メンバー名',
      'zh_Hans': '成员名字',
    },
    'cky0802g': {
      'en': 'Email',
      'de': 'Email',
      'fr': 'E-mail',
      'ja': 'Eメール',
      'zh_Hans': '电子邮件',
    },
    'v7bnky84': {
      'en': 'Last Active',
      'de': 'letzte Aktivität',
      'fr': 'Dernier actif',
      'ja': '最後にログインした時',
      'zh_Hans': '最后登录',
    },
    'e94lom5g': {
      'en': 'Date Created',
      'de': 'Datum erstellt',
      'fr': 'date créée',
      'ja': '作成日',
      'zh_Hans': '创建日期',
    },
    '9jt3fr7z': {
      'en': 'Status',
      'de': 'Status',
      'fr': 'Statut',
      'ja': '状態',
      'zh_Hans': '状态',
    },
    'nqufq7kf': {
      'en': 'Custom Name',
      'de': 'Benutzerdefinierter Name',
      'fr': 'Nom d\'usage',
      'ja': 'カスタム名',
      'zh_Hans': '自定义名称',
    },
    '5siku1lc': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    '4bu1vv9d': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'vsaedqb5': {
      'en': 'Active',
      'de': 'Aktiv',
      'fr': 'Actif',
      'ja': 'アクティブ',
      'zh_Hans': '积极的',
    },
    'gs8e2s15': {
      'en': 'Custom Name',
      'de': 'Benutzerdefinierter Name',
      'fr': 'Nom d\'usage',
      'ja': 'カスタム名',
      'zh_Hans': '自定义名称',
    },
    '2nlu65by': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'a5hwdklf': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    '5nz4qcab': {
      'en': 'Active',
      'de': 'Aktiv',
      'fr': 'Actif',
      'ja': 'アクティブ',
      'zh_Hans': '积极的',
    },
    'ywcow5ea': {
      'en': 'Custom Name',
      'de': 'Benutzerdefinierter Name',
      'fr': 'Nom d\'usage',
      'ja': 'カスタム名',
      'zh_Hans': '自定义名称',
    },
    'x5s08miw': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'rwsikouj': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'yeo44wfc': {
      'en': 'Active',
      'de': 'Aktiv',
      'fr': 'Actif',
      'ja': 'アクティブ',
      'zh_Hans': '积极的',
    },
    'qx2cgsk9': {
      'en': 'Custom Name',
      'de': 'Benutzerdefinierter Name',
      'fr': 'Nom d\'usage',
      'ja': 'カスタム名',
      'zh_Hans': '自定义名称',
    },
    's5qy7ebv': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'f6ku8o7l': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    '6olcuy5s': {
      'en': 'Active',
      'de': 'Aktiv',
      'fr': 'Actif',
      'ja': 'アクティブ',
      'zh_Hans': '积极的',
    },
    'uqjxfdlo': {
      'en': 'Custom Name',
      'de': 'Benutzerdefinierter Name',
      'fr': 'Nom d\'usage',
      'ja': 'カスタム名',
      'zh_Hans': '自定义名称',
    },
    'xj7d8wa6': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'dweeta1i': {
      'en': 'user@domainname.com',
      'de': 'benutzer@domainname.com',
      'fr': 'utilisateur@nomdomaine.com',
      'ja': 'user@domainname.com',
      'zh_Hans': '用户@域名.com',
    },
    'bhza7q33': {
      'en': 'Active',
      'de': 'Aktiv',
      'fr': 'Actif',
      'ja': 'アクティブ',
      'zh_Hans': '积极的',
    },
    '77iqazch': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // projects_alt
  {
    'ozby6fpm': {
      'en': 'Your Projects',
      'de': 'Ihre Projekte',
      'fr': 'Tes projets',
      'ja': 'あなたのプロジェクト',
      'zh_Hans': '您的项目',
    },
    'x8vjabaa': {
      'en': 'Your projects are below',
      'de': 'Ihre Projekte sind unten',
      'fr': 'Vos projets ci-dessous',
      'ja': 'あなたのプロジェクトは以下のとおりです',
      'zh_Hans': '您的项目如下',
    },
    '96wmfc0j': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'rvvnxldf': {
      'en': 'Recent Projects',
      'de': 'Letzte Projekte',
      'fr': 'les projets récents',
      'ja': '最近のプロジェクト',
      'zh_Hans': '最近的项目',
    },
    'l877nva9': {
      'en': 'A list of all your transactions this week.',
      'de': 'Eine Liste all Ihrer Transaktionen in dieser Woche.',
      'fr': 'Une liste de toutes vos transactions cette semaine.',
      'ja': '今週のすべての取引のリスト。',
      'zh_Hans': '本周所有交易的清单。',
    },
    '3k0vy7qx': {
      'en': 'Medical App',
      'de': 'Medizinische App',
      'fr': 'Application médicale',
      'ja': '医療アプリ',
      'zh_Hans': '医疗应用',
    },
    'fgwrl4m3': {
      'en': 'Project Name',
      'de': 'Projektname',
      'fr': 'nom du projet',
      'ja': 'プロジェクト名',
      'zh_Hans': '项目名称',
    },
    'v5n6na66': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '0m9gbqsl': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'y0n1hklr': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'pnbbpt89': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '97cdo6cl': {
      'en': 'Insurance Calculator',
      'de': 'Versicherungsrechner',
      'fr': 'Calculateur d\'assurance',
      'ja': '保険計算機',
      'zh_Hans': '保险计算器',
    },
    'pd2zfnzz': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '78x3hq93': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'hjjtzblm': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'mlfl6qlm': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'iq9pih2m': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '4l2psnhh': {
      'en': 'Team Tutorials',
      'de': 'Team-Tutorials',
      'fr': 'Tutoriels d\'équipe',
      'ja': 'チーム チュートリアル',
      'zh_Hans': '团队教程',
    },
    'mkypctib': {
      'en': 'The latest tutorials posted by your team.',
      'de': 'Die neuesten Tutorials, die von Ihrem Team gepostet wurden.',
      'fr': 'Les derniers tutos postés par votre équipe.',
      'ja': 'チームが投稿した最新のチュートリアル。',
      'zh_Hans': '您的团队发布的最新教程。',
    },
    '7fdlg2bm': {
      'en': '05:03',
      'de': '05:03',
      'fr': '05:03',
      'ja': '05:03',
      'zh_Hans': '05:03',
    },
    'd9mfy1og': {
      'en': '1.Sketch and userflows within your application',
      'de': '1.Sketch und Userflows innerhalb Ihrer Anwendung',
      'fr': '1.Sketch et flux d\'utilisateurs au sein de votre application',
      'ja': '1.アプリケーション内のスケッチとユーザーフロー',
      'zh_Hans': '1.应用程序中的 Sketch 和用户流程',
    },
    'sa0ik2ay': {
      'en':
          'Sketch and userflows within your application are an important part of any problem! We go over the common use cases in order to not make rookie mistakes.',
      'de':
          'Skizzen und Benutzerabläufe innerhalb Ihrer Anwendung sind ein wichtiger Teil jedes Problems! Wir gehen die üblichen Anwendungsfälle durch, um keine Anfängerfehler zu machen.',
      'fr':
          'Les croquis et les flux d\'utilisateurs au sein de votre application sont une partie importante de tout problème ! Nous passons en revue les cas d\'utilisation courants afin de ne pas commettre d\'erreurs de débutant.',
      'ja':
          'アプリケーション内のスケッチとユーザーフローは、あらゆる問題の重要な部分です!初歩的なミスをしないように、一般的なユースケースについて説明します。',
      'zh_Hans': '应用程序中的草图和用户流是任何问题的重要组成部分！为了不犯菜鸟错误，我们回顾了常见的用例。',
    },
    '5ckpok3e': {
      'en': 'Download',
      'de': 'Download',
      'fr': 'Télécharger',
      'ja': 'ダウンロード',
      'zh_Hans': '下载',
    },
    'jhz9fsa9': {
      'en': '05:03',
      'de': '05:03',
      'fr': '05:03',
      'ja': '05:03',
      'zh_Hans': '05:03',
    },
    '66wtuhmi': {
      'en': '1.Sketch and userflows within your application',
      'de': '1.Sketch und Userflows innerhalb Ihrer Anwendung',
      'fr': '1.Sketch et flux d\'utilisateurs au sein de votre application',
      'ja': '1.アプリケーション内のスケッチとユーザーフロー',
      'zh_Hans': '1.应用程序中的 Sketch 和用户流程',
    },
    'ov9zuxhx': {
      'en':
          'Sketch and userflows within your application are an important part of any problem! We go over the common use cases in order to not make rookie mistakes.',
      'de':
          'Skizzen und Benutzerabläufe innerhalb Ihrer Anwendung sind ein wichtiger Teil jedes Problems! Wir gehen die üblichen Anwendungsfälle durch, um keine Anfängerfehler zu machen.',
      'fr':
          'Les croquis et les flux d\'utilisateurs au sein de votre application sont une partie importante de tout problème ! Nous passons en revue les cas d\'utilisation courants afin de ne pas commettre d\'erreurs de débutant.',
      'ja':
          'アプリケーション内のスケッチとユーザーフローは、あらゆる問題の重要な部分です!初歩的なミスをしないように、一般的なユースケースについて説明します。',
      'zh_Hans': '应用程序中的草图和用户流是任何问题的重要组成部分！为了不犯菜鸟错误，我们回顾了常见的用例。',
    },
    'cemc5hqv': {
      'en': 'Download',
      'de': 'Download',
      'fr': 'Télécharger',
      'ja': 'ダウンロード',
      'zh_Hans': '下载',
    },
    '78v80877': {
      'en': '05:03',
      'de': '05:03',
      'fr': '05:03',
      'ja': '05:03',
      'zh_Hans': '05:03',
    },
    'suuw2xcc': {
      'en': '1.Sketch and userflows within your application',
      'de': '1.Sketch und Userflows innerhalb Ihrer Anwendung',
      'fr': '1.Sketch et flux d\'utilisateurs au sein de votre application',
      'ja': '1.アプリケーション内のスケッチとユーザーフロー',
      'zh_Hans': '1.应用程序中的 Sketch 和用户流程',
    },
    'gvtkelwh': {
      'en':
          'Sketch and userflows within your application are an important part of any problem! We go over the common use cases in order to not make rookie mistakes.',
      'de':
          'Skizzen und Benutzerabläufe innerhalb Ihrer Anwendung sind ein wichtiger Teil jedes Problems! Wir gehen die üblichen Anwendungsfälle durch, um keine Anfängerfehler zu machen.',
      'fr':
          'Les croquis et les flux d\'utilisateurs au sein de votre application sont une partie importante de tout problème ! Nous passons en revue les cas d\'utilisation courants afin de ne pas commettre d\'erreurs de débutant.',
      'ja':
          'アプリケーション内のスケッチとユーザーフローは、あらゆる問題の重要な部分です!初歩的なミスをしないように、一般的なユースケースについて説明します。',
      'zh_Hans': '应用程序中的草图和用户流是任何问题的重要组成部分！为了不犯菜鸟错误，我们回顾了常见的用例。',
    },
    '1ue8ep7m': {
      'en': 'Download',
      'de': 'Download',
      'fr': 'Télécharger',
      'ja': 'ダウンロード',
      'zh_Hans': '下载',
    },
    'el80tljz': {
      'en': 'Notifications',
      'de': 'Benachrichtigungen',
      'fr': 'Avis',
      'ja': '通知',
      'zh_Hans': '通知',
    },
    '9kpsnnzx': {
      'en': 'Below are you new notifications.',
      'de': 'Unten sind Ihre neuen Benachrichtigungen.',
      'fr': 'Vous trouverez ci-dessous de nouvelles notifications.',
      'ja': '以下は新しい通知です。',
      'zh_Hans': '以下是您的新通知。',
    },
    'cd3w7agg': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'l1w4933l': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'zd2zlem4': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'q6mgwuni': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'dbrtxdiz': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '14yc3hcd': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'vtcgew8d': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    '1pzwvue8': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'hou27pfm': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '342az9yw': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'lvdpi6df': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'quulyr0x': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    '6nnbsmvb': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Language
  {
    'cepltokh': {
      'en': 'Hello World',
      'de': 'Hallo Welt',
      'fr': 'Bonjour le monde',
      'ja': 'こんにちは世界',
      'zh_Hans': '你好世界',
    },
    '1ujk81ko': {
      'en': 'English',
      'de': 'Englisch',
      'fr': 'Anglais',
      'ja': '英語',
      'zh_Hans': '英语',
    },
    'qhhqh5l4': {
      'en': 'chinese',
      'de': 'Chinesisch',
      'fr': 'chinois',
      'ja': '中文',
      'zh_Hans': '中文',
    },
    'pa61qrgm': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // mainWebNav
  {
    '21i2vb5f': {
      'en': 'Platinum',
      'de': 'Platin',
      'fr': 'Platine',
      'ja': '白金',
      'zh_Hans': '铂',
    },
    'vc28a6wh': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
    'sgj7ppzr': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
    '6h03nko5': {
      'en': 'Projects',
      'de': 'Projekte',
      'fr': 'Projets',
      'ja': 'プロジェクト',
      'zh_Hans': '项目',
    },
    '5s0r4xwl': {
      'en': 'Team Members',
      'de': 'Teammitglieder',
      'fr': 'Membres de l\'équipe',
      'ja': 'チームメンバー',
      'zh_Hans': '团队成员',
    },
    's86yhnhd': {
      'en': 'Clients',
      'de': 'Kunden',
      'fr': 'Clients',
      'ja': 'クライアント',
      'zh_Hans': '客户',
    },
    'sw33tlrx': {
      'en': 'ORGANIZATION',
      'de': 'ORGANISATION',
      'fr': 'ORGANISME',
      'ja': '組織',
      'zh_Hans': '组织',
    },
    '94z4oqwd': {
      'en': 'Billing',
      'de': 'Abrechnung',
      'fr': 'Facturation',
      'ja': '請求する',
      'zh_Hans': '计费',
    },
    'rn0xcho7': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'fr': 'Réglages',
      'ja': '設定',
      'zh_Hans': '设置',
    },
    '76f2nva8': {
      'en': 'Help Center',
      'de': 'Hilfezentrum',
      'fr': 'Centre d\'aide',
      'ja': 'ヘルプセンター',
      'zh_Hans': '帮助中心',
    },
    'jn3sy1cs': {
      'en': 'Having trouble with Platinum? Contact us below.',
      'de': 'Haben Sie Probleme mit Platinum? Kontaktieren Sie uns unten.',
      'fr': 'Un problème avec Platinum ? Contactez-nous ci-dessous.',
      'ja': 'プラチナでお困りですか？下記までお問い合わせください。',
      'zh_Hans': '铂金有问题吗？请在下方联系我们。',
    },
    'pvwevd9h': {
      'en': 'Go To Help Center',
      'de': 'Gehen Sie zum Hilfecenter',
      'fr': 'Aller au centre d\'aide',
      'ja': 'ヘルプセンターに移動',
      'zh_Hans': '前往帮助中心',
    },
  },
  // mobileNav
  {
    'e3ap1bhd': {
      'en': 'HOME',
      'de': 'ZUHAUSE',
      'fr': 'DOMICILE',
      'ja': '家',
      'zh_Hans': '家',
    },
    'zu0rlxg9': {
      'en': 'DEVICE',
      'de': 'GERÄT',
      'fr': 'APPAREIL',
      'ja': 'デバイス',
      'zh_Hans': '设备',
    },
  },
  // messageBottomSheet
  {
    'ktdkqgbm': {
      'en': 'Your Messages',
      'de': 'Deine Nachrichten',
      'fr': 'Tes messages',
      'ja': 'あなたのメッセージ',
      'zh_Hans': '您的讯息',
    },
    '2il0e6ew': {
      'en': 'Below are your new messages',
      'de': 'Unten sind Ihre neuen Nachrichten',
      'fr': 'Ci-dessous vos nouveaux messages',
      'ja': '以下はあなたの新しいメッセージです',
      'zh_Hans': '以下是您的新消息',
    },
    'hlk121nf': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '23b20gjc': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'xacpnb09': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'modh842x': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    '1j0k11dd': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'c3e4q9x4': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'l62ds5ok': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'pqs5d09o': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'qidychpf': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '1ijny0po': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'c5x0vktf': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    '686d70vz': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
  },
  // altNav
  {
    'h834rd3x': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
    'i0qrdyp0': {
      'en': 'Platinum',
      'de': 'Platin',
      'fr': 'Platine',
      'ja': '白金',
      'zh_Hans': '铂',
    },
    'mg2878en': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
    'fwr96f9a': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
    'b86hxizm': {
      'en': 'Projects',
      'de': 'Projekte',
      'fr': 'Projets',
      'ja': 'プロジェクト',
      'zh_Hans': '项目',
    },
    '6w1dznz2': {
      'en': 'Team Members',
      'de': 'Teammitglieder',
      'fr': 'Membres de l\'équipe',
      'ja': 'チームメンバー',
      'zh_Hans': '团队成员',
    },
    'w5r45419': {
      'en': 'Clients',
      'de': 'Kunden',
      'fr': 'Clients',
      'ja': 'クライアント',
      'zh_Hans': '客户',
    },
    '55h9ooma': {
      'en': 'ORGANIZATION',
      'de': 'ORGANISATION',
      'fr': 'ORGANISME',
      'ja': '組織',
      'zh_Hans': '组织',
    },
    'vi5wq5d3': {
      'en': 'Billing',
      'de': 'Abrechnung',
      'fr': 'Facturation',
      'ja': '請求する',
      'zh_Hans': '计费',
    },
    'eiyi9hsu': {
      'en': 'Settings',
      'de': 'Einstellungen',
      'fr': 'Réglages',
      'ja': '設定',
      'zh_Hans': '设置',
    },
  },
  // altNav_2
  {
    'bpjevkz3': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
  },
  // Miscellaneous
  {
    'npbs0pmg': {
      'en': 'Need allow access your contacts',
      'de': 'Sie müssen den Zugriff auf Ihre Kontakte zulassen',
      'fr': 'Besoin d\'autoriser l\'accès à vos contacts',
      'ja': '連絡先へのアクセスを許可する必要があります',
      'zh_Hans': '需要允许访问您的联系人',
    },
    'efnuksla': {
      'en': 'Need allow access your camera',
      'de': 'Sie müssen den Zugriff auf Ihre Kamera zulassen',
      'fr': 'Besoin d\'autoriser l\'accès à votre caméra',
      'ja': 'カメラへのアクセスを許可する必要があります',
      'zh_Hans': '需要允许访问您的相机',
    },
    'mzj4qkwt': {
      'en': 'Need allow receive notifications',
      'de': 'Sie müssen Benachrichtigungen zulassen',
      'fr': 'Besoin d\'autoriser la réception de notifications',
      'ja': '通知の受信を許可する必要があります',
      'zh_Hans': '需要允许接收通知',
    },
  },
].reduce((a, b) => a..addAll(b));
