import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => ['en', 'zh_Hans', 'ja', 'fr', 'de'];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? zh_HansText = '',
    String? jaText = '',
    String? frText = '',
    String? deText = '',
  }) =>
      [enText, zh_HansText, jaText, frText, deText][languageIndex] ?? '';
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // HomePage
  {
    'byoctihc': {
      'en': 'Welcome to DigitalFactory',
      'de': 'Willkommen bei DigitalFactory',
      'fr': 'Bienvenue sur DigitalFactory',
      'ja': 'デジタルファクトリーへようこそ',
      'zh_Hans': '欢迎来到数字工厂',
    },
    '7m5o70u8': {
      'en': 'Hello Guest! Welcome back.',
      'de': 'Hallo Gast! Willkommen zurück.',
      'fr': 'Bonjour Invité ! Content de te revoir.',
      'ja': 'こんにちはゲスト！おかえり。',
      'zh_Hans': '客人您好！欢迎回来。',
    },
    'qbhcr7z8': {
      'en': 'Create',
      'de': 'Schaffen',
      'fr': 'Créer',
      'ja': '作成',
      'zh_Hans': '创造',
    },
    '8dok0sfa': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'hmzlh35e': {
      'en': 'OVERVIEW',
      'de': 'ÜBERBLICK',
      'fr': 'APERÇU',
      'ja': '概要',
      'zh_Hans': '概述',
    },
    'gh6q6yoe': {
      'en': 'TOTAL OUTPUT',
      'de': 'GESAMTLEISTUNG',
      'fr': 'SORTIE TOTALE',
      'ja': '総生産高',
      'zh_Hans': '总产出',
    },
    'saf5ng86': {
      'en': '500.20B',
      'de': '500.20B',
      'fr': '500.20B',
      'ja': '500.20B',
      'zh_Hans': '500.20B',
    },
    '21x8wjwg': {
      'en': 'AVG EFFICENCY ',
      'de': 'DURCHSCHNITTLICHE EFFIZIENZ',
      'fr': 'EFFICACITÉ MOYENNE',
      'ja': '平均効率',
      'zh_Hans': '平均效率',
    },
    'nilobwjj': {
      'en': '95.76%',
      'de': '95,76 %',
      'fr': '95,76 %',
      'ja': '95.76%',
      'zh_Hans': '95.76%',
    },
    '10re4v7b': {
      'en': 'OUTPUT TODAY',
      'de': 'AUSGABE HEUTE',
      'fr': 'SORTIE AUJOURD\'HUI',
      'ja': '今日のアウトプット',
      'zh_Hans': '今天的产量',
    },
    'arnt20hm': {
      'en': '0.25M',
      'de': '0,25 M',
      'fr': '0.25M',
      'ja': '0.25M',
      'zh_Hans': '0.25M',
    },
    'sgyjfrph': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    '4vnhjwga': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    'i3pymgyw': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    'ven1qpwz': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    'zgvfsj1c': {
      'en': 'Notifications',
      'de': 'Benachrichtigungen',
      'fr': 'Avis',
      'ja': '通知',
      'zh_Hans': '通知',
    },
    'vi2nyjjh': {
      'en': 'Below are you new notifications.',
      'de': 'Unten sind Ihre neuen Benachrichtigungen.',
      'fr': 'Vous trouverez ci-dessous de nouvelles notifications.',
      'ja': '以下は新しい通知です。',
      'zh_Hans': '以下是您的新通知。',
    },
    'w20qzy9r': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'cunsd5z0': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'e2vfwyui': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'gw7j3ise': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'j1uzjil0': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'vww8fm3v': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'vrl92nk0': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'ypwg6dnl': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    '3gcwkub9': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'qjifeynz': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'qo1r6531': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'gxsnut94': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'y3jglg7t': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // devices
  {
    'vibf8vqe': {
      'en': 'Your Device',
      'de': 'Ihr Gerät',
      'fr': 'Votre appareil',
      'ja': 'あなたのデバイス',
      'zh_Hans': '你的设备',
    },
    'wqd27t6p': {
      'en': 'Your projects are below',
      'de': 'Ihre Projekte sind unten',
      'fr': 'Vos projets ci-dessous',
      'ja': 'あなたのプロジェクトは以下のとおりです',
      'zh_Hans': '您的项目如下',
    },
    'cthhf2m6': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'wl92yxg8': {
      'en': 'Notifications',
      'de': 'Benachrichtigungen',
      'fr': 'Avis',
      'ja': '通知',
      'zh_Hans': '通知',
    },
    '88ighwvg': {
      'en': 'Below are you new notifications.',
      'de': 'Unten sind Ihre neuen Benachrichtigungen.',
      'fr': 'Vous trouverez ci-dessous de nouvelles notifications.',
      'ja': '以下は新しい通知です。',
      'zh_Hans': '以下是您的新通知。',
    },
    'dow75c37': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'imvp4zoh': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'yg0bk3bt': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'x42j95vy': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'zp6iay4z': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'ydsh35x3': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'pgfbshj3': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'x3mgsj5a': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'qu81rf0d': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '6yl6afsi': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'ohgm7pn6': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'yvgap105': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'ryjm6uw3': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // responsiveTest
  {
    'cbhgiwm8': {
      'en': 'Your Projects',
      'de': 'Ihre Projekte',
      'fr': 'Tes projets',
      'ja': 'あなたのプロジェクト',
      'zh_Hans': '您的项目',
    },
    '0sls6kw7': {
      'en': 'Your projects are below, check it out.',
      'de': 'Ihre Projekte sind unten, sehen Sie es sich an.',
      'fr': 'Vos projets sont ci-dessous, consultez-les.',
      'ja': 'あなたのプロジェクトは以下にあります。チェックしてください。',
      'zh_Hans': '你的项目在下面，检查一下。',
    },
    '53zys4hr': {
      'en': '1',
      'de': '1',
      'fr': '1',
      'ja': '1',
      'zh_Hans': '1个',
    },
    'tvwlt2ke': {
      'en': 'Credit Card',
      'de': 'Kreditkarte',
      'fr': 'Carte de crédit',
      'ja': 'クレジットカード',
      'zh_Hans': '信用卡',
    },
    '2w8mpf1g': {
      'en': 'Budget',
      'de': 'Budget',
      'fr': 'Budget',
      'ja': 'バジェット',
      'zh_Hans': '预算',
    },
    '1m15wkzq': {
      'en': 'Balance',
      'de': 'Balance',
      'fr': 'Solde',
      'ja': 'バランス',
      'zh_Hans': '平衡',
    },
    'c871wtzn': {
      'en': '\$7,630',
      'de': '\$7.630',
      'fr': '7 630 \$',
      'ja': '\$7,630',
      'zh_Hans': '\$7,630',
    },
    'dasfz3nr': {
      'en': '**** 0149',
      'de': '**** 0149',
      'fr': '**** 0149',
      'ja': '**** 0149',
      'zh_Hans': '**** 0149',
    },
    'zdy0xzhd': {
      'en': '05/25',
      'de': '25.05',
      'fr': '25/05',
      'ja': '05/25',
      'zh_Hans': '05/25',
    },
    'o0491zf3': {
      'en': 'Spending',
      'de': 'Ausgaben',
      'fr': 'Dépenses',
      'ja': '支出',
      'zh_Hans': '开支',
    },
    'l7olqxp3': {
      'en': 'Tab View 2',
      'de': 'Registerkartenansicht 2',
      'fr': 'Onglet Affichage 2',
      'ja': 'タブ ビュー 2',
      'zh_Hans': '选项卡视图 2',
    },
    'v68aozff': {
      'en': 'Balance',
      'de': 'Balance',
      'fr': 'Solde',
      'ja': 'バランス',
      'zh_Hans': '平衡',
    },
    'thih5h3p': {
      'en': 'Avg. Spend',
      'de': 'Durchschn. Ausgeben',
      'fr': 'Moy. Passer',
      'ja': '平均払う',
      'zh_Hans': '平均。花费',
    },
    't4di97cf': {
      'en': '\$25,205',
      'de': '25.205 \$',
      'fr': '25 205 \$',
      'ja': '\$25,205',
      'zh_Hans': '25,205 美元',
    },
    'gk4ap4gt': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    '2msyutna': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    'pmfnbk4l': {
      'en': 'Timeline',
      'de': 'Zeitleiste',
      'fr': 'Chronologie',
      'ja': 'タイムライン',
      'zh_Hans': '时间线',
    },
    'zzw80byt': {
      'en': 'Spend',
      'de': 'Ausgeben',
      'fr': 'Passer',
      'ja': '払う',
      'zh_Hans': '花费',
    },
    '51d9zxo7': {
      'en': 'Recent Transactions',
      'de': 'kürzliche Transaktionen',
      'fr': 'transactions récentes',
      'ja': '最近の取引',
      'zh_Hans': '最近的交易',
    },
    'qqt7nhgo': {
      'en': 'A list of all your transactions this week.',
      'de': 'Eine Liste all Ihrer Transaktionen in dieser Woche.',
      'fr': 'Une liste de toutes vos transactions cette semaine.',
      'ja': '今週のすべての取引のリスト。',
      'zh_Hans': '本周所有交易的清单。',
    },
    'zget5n63': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '1p9sfg9v': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'aznzw4f3': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '4ez6kftz': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'uht4kun8': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'z30jzbsw': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '7ztbb7zd': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '5k3maxgv': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'hilwrd84': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '8wa8dc97': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'hlkotqx2': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '5wkzee24': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    '31lfef1e': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    'qcmezt7g': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'o2zwpyto': {
      'en': 'Insurance',
      'de': 'Versicherung',
      'fr': 'Assurance',
      'ja': '保険',
      'zh_Hans': '保险',
    },
    '4f0sx62l': {
      'en': 'Property Coverage',
      'de': 'Eigentumsabdeckung',
      'fr': 'Couverture des biens',
      'ja': 'プロパティカバレッジ',
      'zh_Hans': '财产保险',
    },
    'pdo5ovag': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
  },
  // Language
  {
    'cepltokh': {
      'en': 'Hello World',
      'de': 'Hallo Welt',
      'fr': 'Bonjour le monde',
      'ja': 'こんにちは世界',
      'zh_Hans': '你好世界',
    },
    '1ujk81ko': {
      'en': 'English',
      'de': 'Englisch',
      'fr': 'Anglais',
      'ja': '英語',
      'zh_Hans': '英语',
    },
    'qhhqh5l4': {
      'en': 'chinese',
      'de': 'Chinesisch',
      'fr': 'chinois',
      'ja': '中文',
      'zh_Hans': '中文',
    },
    'pa61qrgm': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // profile
  {
    'g7a9ubvk': {
      'en': 'Your Profile',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'y8r21px7': {
      'en': 'Below are your settings',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'lsa3dnot': {
      'en': 'Edit Profile',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'atjmsjjh': {
      'en': 'Account',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'qkrv2bbz': {
      'en': 'Switch to Dark Mode',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'mzdf244x': {
      'en': 'Switch to Light Mode',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '0pqq7woz': {
      'en': 'Country',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'oc5e0851': {
      'en': 'Edit Profile',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ufl5u4ev': {
      'en': 'General',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'yy4qns49': {
      'en': 'Support',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '4mxcp5ue': {
      'en': 'Terms of Service',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '4olua3mt': {
      'en': 'Invite Friends',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'jpn9srkz': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // signIn
  {
    'l3jtteyk': {
      'en': 'Welcome Back!',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '434j7haa': {
      'en': 'Use the form below to access your account.',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ww97lzg7': {
      'en': 'Email Address',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'iv5zm6wu': {
      'en': 'Enter your email here...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'o1gy8z12': {
      'en': 'Password',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '3iaref0k': {
      'en': 'Enter your email here...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'kxs6g3e2': {
      'en': 'Forgot Password?',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'rx9s8vlm': {
      'en': 'Sign In',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'hf3mjvyg': {
      'en': 'Use a social platform to continue',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'fpxabyiz': {
      'en': 'Don\'t have an account?',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ygxbi7qu': {
      'en': 'Create Account',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'g1ppos5t': {
      'en': 'Continue as Guest',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'qu6bbsv3': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // signUp
  {
    'w9u89e4f': {
      'en': 'Get Started',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'kt7hjvcx': {
      'en': 'Create an account by using the form below.',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ah46mbj9': {
      'en': 'Email Address',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '62bpeczy': {
      'en': 'Enter your email here...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'm5gwsv7q': {
      'en': 'Password',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'pvp695f6': {
      'en': 'Enter your email here...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'dsyxd0d7': {
      'en': 'Sign Up',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '39tixtfd': {
      'en': 'Use a social platform to continue',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'yat8s6jj': {
      'en': 'Already have an account?',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'que6w7oj': {
      'en': 'Login',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'tpr5ninx': {
      'en': 'Continue as Guest',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'kkwa4e9z': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // createProfile
  {
    'lz5owbq9': {
      'en': 'Create Profile',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '36zkph5y': {
      'en': 'Your Name',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '9b8owyq9': {
      'en': 'Your City',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'sum5me41': {
      'en': 'State',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '1o58ylc8': {
      'en': 'State',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ay0cik2y': {
      'en': 'Alabama',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'th2bk0ym': {
      'en': 'Alaska',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'mc2ayhfs': {
      'en': 'Arizona',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '68lvaold': {
      'en': 'Arkansas',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'nvvqueql': {
      'en': 'California',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '9xsa6ulp': {
      'en': 'Colorado',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'yj2hqlt6': {
      'en': 'Connecticut',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'b7u2za9g': {
      'en': 'Delaware',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '55w6ie82': {
      'en': 'Florida',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'kjbrasqs': {
      'en': 'Georgia',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'uuo8ki6q': {
      'en': 'Hawaii',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'hhwyn2dk': {
      'en': 'Idaho',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'dj1e0s6x': {
      'en': 'Illinoi',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'wn461ugw': {
      'en': 'Indiana',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'e8pmqdt1': {
      'en': 'Iowa',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '3hrdqq3c': {
      'en': 'Kansas',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'fvrahmi7': {
      'en': 'Kentucky',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'wb3ikwta': {
      'en': 'Louisiana',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'tjvipti1': {
      'en': 'Maine',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '5odq2qqr': {
      'en': 'Maryland',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'sh02ys3b': {
      'en': 'Massachusetts',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'lqy7mzrt': {
      'en': 'Michigan',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'vrqzvcxf': {
      'en': 'Minnesota',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '5ims9zun': {
      'en': 'Mississippi',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'a64visv7': {
      'en': 'Missouri',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '99umqkel': {
      'en': 'Monta',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'hyx3ekee': {
      'en': 'Nebraska',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'i3yeihf3': {
      'en': 'Nevada',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'o0gwfqbr': {
      'en': 'New Hampshire',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    't6kool76': {
      'en': 'New Jersey',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'mz5f7e1v': {
      'en': 'New Mexico',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'yqx1zzdr': {
      'en': 'New York',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'qo18yil9': {
      'en': 'North Carolina',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '34kafr09': {
      'en': 'North Dak',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ozhlxcej': {
      'en': 'Ohio',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ybp2nkcd': {
      'en': 'Oklahoma',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '1o6usb34': {
      'en': 'Oregon',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'j0i4djdx': {
      'en': 'Pennsylvani',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ahc6i725': {
      'en': 'Rhode Island',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'i0jrtggw': {
      'en': 'South Caroli',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '2802yhp8': {
      'en': 'South Dakota',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'cq5eyvxl': {
      'en': 'Tennessee',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'f1mx1412': {
      'en': 'Texas',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'qguuu1sz': {
      'en': 'Utah',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'jgpzvhmv': {
      'en': 'Vermont',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'bvyggt92': {
      'en': 'Virginia',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'tqdfvsp1': {
      'en': 'Washingto',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '2ovydsma': {
      'en': 'West Virginia',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'b9mjv7of': {
      'en': 'Wisconsin',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    's8ctapc3': {
      'en': 'Wyoming',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '6cvw6ch4': {
      'en': 'Select State',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'gty9x3ww': {
      'en': 'Your bio',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'nw1bqay5': {
      'en': 'Save Changes',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'rdqckjrg': {
      'en': 'Create Profile',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '6vudafy9': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // forgotPassword
  {
    'ras9m6jp': {
      'en': 'Forgot Password',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'f1s90q8z': {
      'en':
          'We will send you an email with a link to reset your password, please enter the email associated with your account below.',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ud7wgzwo': {
      'en': 'Your email',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '0ky26p03': {
      'en': 'Enter your email to recieve a linke...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'yb27uqqt': {
      'en': 'Send Reset Link',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'jfzc1pwu': {
      'en': 'Forgot Password',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'c38whx8c': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // phoneSignIn
  {
    'm5c3sn4w': {
      'en': 'Phone Sign In',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'nc9hgomf': {
      'en': 'Phone Sign In',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'vh0ol8x0': {
      'en': 'Type in your phone number below to register.',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'oiqpo6i0': {
      'en': 'Your Phone Number',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ky1o0pxp': {
      'en': 'Please enter a valid number...',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'ez876eyy': {
      'en': 'Sign In with Phone',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'zp3fev4b': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // phoneVerify
  {
    'ywoaexn6': {
      'en': 'PhoneVerify',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'v49uj5mr': {
      'en': 'Confirm your Code',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    '15bs0a8b': {
      'en': 'This code helps keep your account safe and secure.',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'k9r2d5dd': {
      'en': 'Confirm & Continue',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
    'vazm1640': {
      'en': 'Home',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // mainWebNav
  {
    '21i2vb5f': {
      'en': 'DigitalFactory',
      'de': 'Platin',
      'fr': 'Platine',
      'ja': '白金',
      'zh_Hans': '铂',
    },
    'vc28a6wh': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
    'sgj7ppzr': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
    '6h03nko5': {
      'en': 'Devices',
      'de': 'Projekte',
      'fr': 'Projets',
      'ja': 'プロジェクト',
      'zh_Hans': '项目',
    },
    'sw33tlrx': {
      'en': 'ORGANIZATION',
      'de': 'ORGANISATION',
      'fr': 'ORGANISME',
      'ja': '組織',
      'zh_Hans': '组织',
    },
    'rn0xcho7': {
      'en': 'Profile',
      'de': 'Einstellungen',
      'fr': 'Réglages',
      'ja': '設定',
      'zh_Hans': '设置',
    },
    '76f2nva8': {
      'en': 'Help Center',
      'de': 'Hilfezentrum',
      'fr': 'Centre d\'aide',
      'ja': 'ヘルプセンター',
      'zh_Hans': '帮助中心',
    },
    'jn3sy1cs': {
      'en': 'Having trouble with Platinum? Contact us below.',
      'de': 'Haben Sie Probleme mit Platinum? Kontaktieren Sie uns unten.',
      'fr': 'Un problème avec Platinum ? Contactez-nous ci-dessous.',
      'ja': 'プラチナでお困りですか？下記までお問い合わせください。',
      'zh_Hans': '铂金有问题吗？请在下方联系我们。',
    },
    'pvwevd9h': {
      'en': 'Go To Help Center',
      'de': 'Gehen Sie zum Hilfecenter',
      'fr': 'Aller au centre d\'aide',
      'ja': 'ヘルプセンターに移動',
      'zh_Hans': '前往帮助中心',
    },
  },
  // mobileNav
  {
    'e3ap1bhd': {
      'en': 'Home',
      'de': 'ZUHAUSE',
      'fr': 'DOMICILE',
      'ja': '家',
      'zh_Hans': '家',
    },
    'zu0rlxg9': {
      'en': 'Devices',
      'de': 'GERÄT',
      'fr': 'APPAREIL',
      'ja': 'デバイス',
      'zh_Hans': '设备',
    },
    'anet0juh': {
      'en': 'Profile',
      'de': 'GERÄT',
      'fr': 'APPAREIL',
      'ja': 'デバイス',
      'zh_Hans': '设备',
    },
  },
  // messageBottomSheet
  {
    'ktdkqgbm': {
      'en': 'Your Messages',
      'de': 'Deine Nachrichten',
      'fr': 'Tes messages',
      'ja': 'あなたのメッセージ',
      'zh_Hans': '您的讯息',
    },
    '2il0e6ew': {
      'en': 'Below are your new messages',
      'de': 'Unten sind Ihre neuen Nachrichten',
      'fr': 'Ci-dessous vos nouveaux messages',
      'ja': '以下はあなたの新しいメッセージです',
      'zh_Hans': '以下是您的新消息',
    },
    'hlk121nf': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '23b20gjc': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'xacpnb09': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'modh842x': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    '1j0k11dd': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    'c3e4q9x4': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'l62ds5ok': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    'pqs5d09o': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
    'qidychpf': {
      'en': 'Username here',
      'de': 'Benutzername hier',
      'fr': 'Nom d\'utilisateur ici',
      'ja': 'ユーザー名はこちら',
      'zh_Hans': '用户名在这里',
    },
    '1ijny0po': {
      'en': 'okay wow, you could definitely catch meat the restaurant in Ibiza',
      'de':
          'Okay, wow, Fleisch kann man definitiv im Restaurant auf Ibiza fangen',
      'fr':
          'ok wow, vous pourriez certainement attraper de la viande au restaurant à Ibiza',
      'ja': 'わかりました、イビサ島のレストランで間違いなく肉を釣ることができました',
      'zh_Hans': '好的哇，你绝对可以在伊维萨岛的餐厅吃肉',
    },
    'c5x0vktf': {
      'en': 'Posted',
      'de': 'Gesendet',
      'fr': 'Posté',
      'ja': '投稿しました',
      'zh_Hans': '发表',
    },
    '686d70vz': {
      'en': 'A few moments ago',
      'de': 'Vor ein paar Augenblicken',
      'fr': 'Il y a quelques instants',
      'ja': '少し前',
      'zh_Hans': '几分钟前',
    },
  },
  // altNav
  {
    'h834rd3x': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
    'i0qrdyp0': {
      'en': 'DigitalFacotry',
      'de': 'Platin',
      'fr': 'Platine',
      'ja': '白金',
      'zh_Hans': '铂',
    },
    'mg2878en': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
    'fwr96f9a': {
      'en': 'Home',
      'de': 'Zuhause',
      'fr': 'Domicile',
      'ja': '家',
      'zh_Hans': '家',
    },
    'b86hxizm': {
      'en': 'Devices',
      'de': 'Projekte',
      'fr': 'Projets',
      'ja': 'プロジェクト',
      'zh_Hans': '项目',
    },
    '55h9ooma': {
      'en': 'ORGANIZATION',
      'de': 'ORGANISATION',
      'fr': 'ORGANISME',
      'ja': '組織',
      'zh_Hans': '组织',
    },
    'vi5wq5d3': {
      'en': 'Profile',
      'de': 'Abrechnung',
      'fr': 'Facturation',
      'ja': '請求する',
      'zh_Hans': '计费',
    },
  },
  // altNav_2
  {
    'bpjevkz3': {
      'en': 'MENU',
      'de': 'SPEISEKARTE',
      'fr': 'MENU',
      'ja': 'メニュー',
      'zh_Hans': '菜单',
    },
  },
  // deviceListItem
  {
    'dlc9eg2k': {
      'en': 'Today amount',
      'de': '',
      'fr': '',
      'ja': '',
      'zh_Hans': '',
    },
  },
  // Miscellaneous
  {
    'npbs0pmg': {
      'en': 'Need allow access your contacts',
      'de': 'Sie müssen den Zugriff auf Ihre Kontakte zulassen',
      'fr': 'Besoin d\'autoriser l\'accès à vos contacts',
      'ja': '連絡先へのアクセスを許可する必要があります',
      'zh_Hans': '需要允许访问您的联系人',
    },
    'efnuksla': {
      'en': 'Need allow access your camera',
      'de': 'Sie müssen den Zugriff auf Ihre Kamera zulassen',
      'fr': 'Besoin d\'autoriser l\'accès à votre caméra',
      'ja': 'カメラへのアクセスを許可する必要があります',
      'zh_Hans': '需要允许访问您的相机',
    },
    'mzj4qkwt': {
      'en': 'Need allow receive notifications',
      'de': 'Sie müssen Benachrichtigungen zulassen',
      'fr': 'Besoin d\'autoriser la réception de notifications',
      'ja': '通知の受信を許可する必要があります',
      'zh_Hans': '需要允许接收通知',
    },
  },
].reduce((a, b) => a..addAll(b));
